# Set the prefix to C-a
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Window Management
bind-key C-c new-window -c "#{pane_current_path}"
bind-key C-d detach
bind-key K confirm-before "kill-window"

# Window Movement
unbind-key n
unbind-key p
bind-key H previous-window
bind-key L next-window
bind-key C-a last-window

# Pane Split
unbind-key '"'
unbind-key %
unbind-key -
bind-key - split-window -v -c "#{pane_current_path}"
bind-key '\' split-window -h -c "#{pane_current_path}"

# Pane Movement
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key -r C-h resize-pane -L
bind-key -r C-j resize-pane -D
bind-key -r C-k resize-pane -U
bind-key -r C-l resize-pane -R
bind-key f resize-pane -Z

# Copy Mode
set-option -g set-clipboard on
set-option -g mode-keys vi
unbind-key [
unbind-key p
unbind-key -T copy-mode-vi Enter
bind-key v copy-mode
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection c"
bind-key p run "xsel -o | tmux load-buffer - ; tmux paste-buffer"

# Mouse
set-option -g mouse on
unbind-key -T copy-mode-vi mouseDragEnd1Pane

# Scroll Pane (Not Window)
set -g terminal-overrides 'xterm*:smcup@:rmcup@'
set -as terminal-overrides ',*:indn@'

# Renumber Windows on Close
set -g renumber-windows on

# Set Scrollback History
set-option -g history-limit 10000

# Set Indexes Starting At 1
set-option -g base-index 1
set-option -g pane-base-index 1

# Config
bind-key r source-file ~/.tmux.conf \; display "Config Reloaded!"
